### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by Tastaturberuf** [bezin/contao-jquery-chosen#1]
Super praktische Erweiterung!

Kannst du bitte einen Release 1.0.0 erstellen damit man die Erweiterung als "stable" nutzen kann?

**Comment by bezin** [comment]
Hallo, 

das freut uns zuhören. Wir haben soeben den aktuellen Stand als Version 1.0.0 getaggt.

**Comment by Tastaturberuf** [comment]
Vielen Dank. Und jetzt bitte noch das Repository mit Packagist verbinden.
